<?php
/**
 * BankAccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Billit.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BankAccountTest Class Doc Comment
 *
 * @category    Class
 * @description BankAccount
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BankAccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BankAccount"
     */
    public function testBankAccount()
    {
    }

    /**
     * Test attribute "company_id"
     */
    public function testPropertyCompanyId()
    {
    }

    /**
     * Test attribute "bank_account_id"
     */
    public function testPropertyBankAccountId()
    {
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
    }

    /**
     * Test attribute "bic"
     */
    public function testPropertyBic()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "verified"
     */
    public function testPropertyVerified()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "saldo_date"
     */
    public function testPropertySaldoDate()
    {
    }

    /**
     * Test attribute "saldo"
     */
    public function testPropertySaldo()
    {
    }

    /**
     * Test attribute "external_provider_id"
     */
    public function testPropertyExternalProviderId()
    {
    }

    /**
     * Test attribute "logo_file_id"
     */
    public function testPropertyLogoFileId()
    {
    }

    /**
     * Test attribute "logo_file_url"
     */
    public function testPropertyLogoFileUrl()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "coda_by_ing_user"
     */
    public function testPropertyCodaByIngUser()
    {
    }
}
