<?php
/**
 * BookingEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Billit.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BookingEntryTest Class Doc Comment
 *
 * @category    Class
 * @description BookingEntry
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BookingEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BookingEntry"
     */
    public function testBookingEntry()
    {
    }

    /**
     * Test attribute "booking_entry_id"
     */
    public function testPropertyBookingEntryId()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "account_code"
     */
    public function testPropertyAccountCode()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "debet_or_credit"
     */
    public function testPropertyDebetOrCredit()
    {
    }

    /**
     * Test attribute "vat1"
     */
    public function testPropertyVat1()
    {
    }

    /**
     * Test attribute "vat2"
     */
    public function testPropertyVat2()
    {
    }

    /**
     * Test attribute "vat3"
     */
    public function testPropertyVat3()
    {
    }
}
