<?php
/**
 * InboxGetResultItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Billit.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InboxGetResultItemTest Class Doc Comment
 *
 * @category    Class
 * @description InboxGetResultItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InboxGetResultItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InboxGetResultItem"
     */
    public function testInboxGetResultItem()
    {
    }

    /**
     * Test attribute "inbox_item_id"
     */
    public function testPropertyInboxItemId()
    {
    }

    /**
     * Test attribute "sender_peppol_id"
     */
    public function testPropertySenderPeppolId()
    {
    }

    /**
     * Test attribute "peppol_document_type"
     */
    public function testPropertyPeppolDocumentType()
    {
    }

    /**
     * Test attribute "receiver_peppol_id"
     */
    public function testPropertyReceiverPeppolId()
    {
    }

    /**
     * Test attribute "sender_company_id"
     */
    public function testPropertySenderCompanyId()
    {
    }

    /**
     * Test attribute "receiver_company_id"
     */
    public function testPropertyReceiverCompanyId()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "peppol_file_id"
     */
    public function testPropertyPeppolFileId()
    {
    }
}
