<?php
/**
 * PartyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Billit.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PartyTest Class Doc Comment
 *
 * @category    Class
 * @description Party
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PartyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Party"
     */
    public function testParty()
    {
    }

    /**
     * Test attribute "party_id"
     */
    public function testPropertyPartyId()
    {
    }

    /**
     * Test attribute "book_year_start"
     */
    public function testPropertyBookYearStart()
    {
    }

    /**
     * Test attribute "nr"
     */
    public function testPropertyNr()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "commercial_name"
     */
    public function testPropertyCommercialName()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "street_number"
     */
    public function testPropertyStreetNumber()
    {
    }

    /**
     * Test attribute "box"
     */
    public function testPropertyBox()
    {
    }

    /**
     * Test attribute "zipcode"
     */
    public function testPropertyZipcode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
    }

    /**
     * Test attribute "bic"
     */
    public function testPropertyBic()
    {
    }

    /**
     * Test attribute "mobile"
     */
    public function testPropertyMobile()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "contact_first_name"
     */
    public function testPropertyContactFirstName()
    {
    }

    /**
     * Test attribute "contact_last_name"
     */
    public function testPropertyContactLastName()
    {
    }

    /**
     * Test attribute "vat_number"
     */
    public function testPropertyVatNumber()
    {
    }

    /**
     * Test attribute "peppol_identifier"
     */
    public function testPropertyPeppolIdentifier()
    {
    }

    /**
     * Test attribute "rpr"
     */
    public function testPropertyRpr()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "party_type"
     */
    public function testPropertyPartyType()
    {
    }

    /**
     * Test attribute "vat_liable"
     */
    public function testPropertyVatLiable()
    {
    }

    /**
     * Test attribute "accountant_code"
     */
    public function testPropertyAccountantCode()
    {
    }

    /**
     * Test attribute "gl_account_code"
     */
    public function testPropertyGlAccountCode()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "ventilation_code"
     */
    public function testPropertyVentilationCode()
    {
    }

    /**
     * Test attribute "external_provider_id"
     */
    public function testPropertyExternalProviderId()
    {
    }

    /**
     * Test attribute "external_provider_tc"
     */
    public function testPropertyExternalProviderTc()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "bank_accounts"
     */
    public function testPropertyBankAccounts()
    {
    }

    /**
     * Test attribute "default_payment_method_tc"
     */
    public function testPropertyDefaultPaymentMethodTc()
    {
    }

    /**
     * Test attribute "default_paid"
     */
    public function testPropertyDefaultPaid()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "default_transport_type_tc"
     */
    public function testPropertyDefaultTransportTypeTc()
    {
    }

    /**
     * Test attribute "financial_reduction_percentage_default"
     */
    public function testPropertyFinancialReductionPercentageDefault()
    {
    }

    /**
     * Test attribute "financial_reduction_days_default"
     */
    public function testPropertyFinancialReductionDaysDefault()
    {
    }

    /**
     * Test attribute "default_expiry_offset"
     */
    public function testPropertyDefaultExpiryOffset()
    {
    }

    /**
     * Test attribute "gl_default_expiry_offset"
     */
    public function testPropertyGlDefaultExpiryOffset()
    {
    }

    /**
     * Test attribute "role"
     */
    public function testPropertyRole()
    {
    }

    /**
     * Test attribute "internal_info"
     */
    public function testPropertyInternalInfo()
    {
    }

    /**
     * Test attribute "vat_deductable"
     */
    public function testPropertyVatDeductable()
    {
    }

    /**
     * Test attribute "default_reduction_percentage"
     */
    public function testPropertyDefaultReductionPercentage()
    {
    }
}
