<?php
/**
 * VatGroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Billit.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VatGroupTest Class Doc Comment
 *
 * @category    Class
 * @description VatGroup
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VatGroupTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VatGroup"
     */
    public function testVatGroup()
    {
    }

    /**
     * Test attribute "ventilation_code"
     */
    public function testPropertyVentilationCode()
    {
    }

    /**
     * Test attribute "vat_percentage"
     */
    public function testPropertyVatPercentage()
    {
    }

    /**
     * Test attribute "total_excl"
     */
    public function testPropertyTotalExcl()
    {
    }

    /**
     * Test attribute "total_vat"
     */
    public function testPropertyTotalVat()
    {
    }

    /**
     * Test attribute "total_incl"
     */
    public function testPropertyTotalIncl()
    {
    }

    /**
     * Test attribute "mtvh"
     */
    public function testPropertyMtvh()
    {
    }

    /**
     * Test attribute "financial_reduction_amount"
     */
    public function testPropertyFinancialReductionAmount()
    {
    }
}
