<?php
/**
 * OrderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Billit.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for orderGetDeleted
     *
     * .
     *
     */
    public function testOrderGetDeleted()
    {
    }

    /**
     * Test case for orderGetOrders
     *
     * .
     *
     */
    public function testOrderGetOrders()
    {
    }

    /**
     * Test case for orderGetOrders_0
     *
     * .
     *
     */
    public function testOrderGetOrders0()
    {
    }

    /**
     * Test case for orderPatchOrders
     *
     * .
     *
     */
    public function testOrderPatchOrders()
    {
    }

    /**
     * Test case for orderPostOrderPayment
     *
     * .
     *
     */
    public function testOrderPostOrderPayment()
    {
    }

    /**
     * Test case for orderPostOrders
     *
     * .
     *
     */
    public function testOrderPostOrders()
    {
    }

    /**
     * Test case for orderPostSend
     *
     * .
     *
     */
    public function testOrderPostSend()
    {
    }

    /**
     * Test case for orderPutOrderBookings
     *
     * .
     *
     */
    public function testOrderPutOrderBookings()
    {
    }
}
